# This docker-compose yml describe the services to run locally
version: '2'

# Defines the services
services:

  # Test image (packages, services, scripts)
  test-image:
    image: bandsintown/alpine-test:${VERSION}
    command: bash
    depends_on:
      - consul
    environment:
      - VERSION=${VERSION}
      - CONSUL_ADDRESS=consul:8500

  # Debug tests for DNSMASQ with only one DNS Nameserver and Search Domain
  test-dns:
    extends:
      file: tests.yml
      service: test-dns
    command: bash
    stdin_open: true
    tty: true
    working_dir: /tests/go-dnsmasq

  # Debug tests for DNSMASQ with Multiple DNS Nameserver and Search Domain
  test-dns-multiple:
     extends:
       file: tests.yml
       service: test-dns-multiple
     command: bash
     stdin_open: true
     tty: true
     working_dir: /tests/go-dnsmasq

  # Test debug  with Multiple DNS Nameserver and Search Domain
  test-dns-multiple:
     extends:
       file: tests.yml
       service: test-dns-multiple
     command: bash
     depends_on:
       - consul
     stdin_open: true
     tty: true
     working_dir: /tests/go-dnsmasq

  # Test debug for consul template
  test-consul-template:
    image: bandsintown/alpine-test:${VERSION}
    command: bash
    depends_on:
      - consul
    environment:
      - DISABLE_CONSUL_TEMPLATE=true
      - CONSUL_ADDRESS=consul:8500
      - S6_LOGGING=1
      - VERSION=${VERSION}
    volumes:
      - ./tests:/tests
      - ./tests/consul-template/etc:/etc/consul-template
    stdin_open: true
    tty: true
    working_dir: /tests/consul-template

  # Consul
  consul:
    image: consul
    command: "agent -dev -client 0.0.0.0 -ui"
    ports:
      - 8500
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    # We disable the log in order to increase lisibility in CI
    logging:
      driver: "none"